// <auto-generated />
using System;
using DailyRpg.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyRPG.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251120221951_AddStreakFields")]
    partial class AddStreakFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DailyRpg.Models.BattleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnemyCurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("EnemyMaxHp")
                        .HasColumnType("int");

                    b.Property<int>("HunterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OpponentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("PlayerMaxHp")
                        .HasColumnType("int");

                    b.Property<bool>("PlayerWon")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("BattleSession");
                });

            modelBuilder.Entity("DailyRpg.Models.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NextBossId")
                        .HasColumnType("int");

                    b.Property<int>("RewardCoin")
                        .HasColumnType("int");

                    b.Property<int>("RewardXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("DailyRpg.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinReward")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HunterUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HunterUserId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("DailyRpg.Models.HunterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributePoints")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBossHp")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentBossId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentCoins")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedArmorSlotId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippedWeaponSlotId")
                        .HasColumnType("int");

                    b.Property<string>("HunterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("NextLevelXp")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("XpDouble")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBossId");

                    b.HasIndex("EquippedArmorSlotId");

                    b.HasIndex("EquippedWeaponSlotId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StatsUser");
                });

            modelBuilder.Entity("DailyRpg.Models.InventorySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HunterUserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HunterUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventorySlots");
                });

            modelBuilder.Entity("DailyRpg.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EffectValue")
                        .HasColumnType("int");

                    b.Property<int>("EquipType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShopPrice")
                        .HasColumnType("int");

                    b.Property<string>("SkillAffinity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DailyRpg.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemCreatedId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ItemCreatedId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DailyRpg.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("DailyRpg.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DailyRpg.Models.Contract", b =>
                {
                    b.HasOne("DailyRpg.Models.HunterUser", "HunterUser")
                        .WithMany()
                        .HasForeignKey("HunterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HunterUser");
                });

            modelBuilder.Entity("DailyRpg.Models.HunterUser", b =>
                {
                    b.HasOne("DailyRpg.Models.Boss", "CurrentBoss")
                        .WithMany()
                        .HasForeignKey("CurrentBossId");

                    b.HasOne("DailyRpg.Models.InventorySlot", "EquippedArmorSlot")
                        .WithMany()
                        .HasForeignKey("EquippedArmorSlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DailyRpg.Models.InventorySlot", "EquippedWeaponSlot")
                        .WithMany()
                        .HasForeignKey("EquippedWeaponSlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DailyRpg.Models.User", null)
                        .WithOne("HunterUser")
                        .HasForeignKey("DailyRpg.Models.HunterUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentBoss");

                    b.Navigation("EquippedArmorSlot");

                    b.Navigation("EquippedWeaponSlot");
                });

            modelBuilder.Entity("DailyRpg.Models.InventorySlot", b =>
                {
                    b.HasOne("DailyRpg.Models.HunterUser", "HunterUser")
                        .WithMany("InventorySlots")
                        .HasForeignKey("HunterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyRpg.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HunterUser");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("DailyRpg.Models.Recipe", b =>
                {
                    b.HasOne("DailyRpg.Models.Item", "ItemCreated")
                        .WithMany()
                        .HasForeignKey("ItemCreatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCreated");
                });

            modelBuilder.Entity("DailyRpg.Models.RecipeIngredient", b =>
                {
                    b.HasOne("DailyRpg.Models.Item", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyRpg.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DailyRpg.Models.HunterUser", b =>
                {
                    b.Navigation("InventorySlots");
                });

            modelBuilder.Entity("DailyRpg.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("DailyRpg.Models.User", b =>
                {
                    b.Navigation("HunterUser")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
